// Database seed data for development
export const seedData = {
  users: [
    {
      id: "user-1",
      name: "Rajesh Kumar",
      email: "patient@example.com",
      password: "password123",
      role: "patient",
    },
    {
      id: "user-2",
      name: "Dr. Priya Sharma",
      email: "doctor@example.com",
      password: "password123",
      role: "doctor",
      specialization: "General Medicine",
    },
    {
      id: "user-3",
      name: "Admin User",
      email: "admin@example.com",
      password: "password123",
      role: "admin",
    },
  ],

  symptoms: [
    {
      id: "sym-1",
      name: "Fever",
      nameHi: "बुखार",
      nameMr: "ताप",
      category: "Systemic",
    },
    {
      id: "sym-2",
      name: "Cough",
      nameHi: "खांसी",
      nameMr: "खोकला",
      category: "Respiratory",
    },
    {
      id: "sym-3",
      name: "Headache",
      nameHi: "सिरदर्द",
      nameMr: "डोकेदुखी",
      category: "Neurological",
    },
    {
      id: "sym-4",
      name: "Fatigue",
      nameHi: "थकान",
      nameMr: "थकव",
      category: "Systemic",
    },
    {
      id: "sym-5",
      name: "Sore Throat",
      nameHi: "गले में दर्द",
      nameMr: "घशाला दुखणे",
      category: "Respiratory",
    },
    {
      id: "sym-6",
      name: "Body Aches",
      nameHi: "शरीर में दर्द",
      nameMr: "शरीरात दुखणे",
      category: "Musculoskeletal",
    },
    {
      id: "sym-7",
      name: "Shortness of Breath",
      nameHi: "सांस की कमी",
      nameMr: "श्वासाचा त्रास",
      category: "Respiratory",
    },
    {
      id: "sym-8",
      name: "Chest Pain",
      nameHi: "छाती में दर्द",
      nameMr: "छातीचा दुखणे",
      category: "Cardiovascular",
    },
  ],

  conditions: [
    {
      id: "cond-1",
      name: "Common Cold",
      nameHi: "सामान्य सर्दी",
      nameMr: "सामान्य सर्दी",
      severity: "low",
    },
    {
      id: "cond-2",
      name: "Influenza",
      nameHi: "इन्फ्लूएंजा",
      nameMr: "इन्फ्लूएंजा",
      severity: "medium",
    },
    {
      id: "cond-3",
      name: "COVID-19",
      nameHi: "कोविड-19",
      nameMr: "कोविड-19",
      severity: "high",
    },
    {
      id: "cond-4",
      name: "Bronchitis",
      nameHi: "ब्रोंकाइटिस",
      nameMr: "ब्रोंकाइटिस",
      severity: "medium",
    },
    {
      id: "cond-5",
      name: "Migraine",
      nameHi: "माइग्रेन",
      nameMr: "माइग्रेन",
      severity: "medium",
    },
    {
      id: "cond-6",
      name: "Hypertension",
      nameHi: "उच्च रक्तचाप",
      nameMr: "उच्च रक्तचाप",
      severity: "high",
    },
  ],

  medicines: [
    {
      id: "med-1",
      name: "Paracetamol",
      nameHi: "पेरासिटामोल",
      nameMr: "पेरासिटामोल",
      class: "Analgesic",
      dose: "500mg",
      frequency: "3-4 times daily",
      description: "For fever and pain relief",
    },
    {
      id: "med-2",
      name: "Amoxicillin",
      nameHi: "एमॉक्सिसिलिन",
      nameMr: "एमॉक्सिसिलिन",
      class: "Antibiotic",
      dose: "250-500mg",
      frequency: "3 times daily",
      description: "Broad-spectrum antibiotic",
    },
    {
      id: "med-3",
      name: "Aspirin",
      nameHi: "एस्पिरिन",
      nameMr: "एस्पिरिन",
      class: "Analgesic/Anti-inflammatory",
      dose: "500mg",
      frequency: "2-3 times daily",
      description: "Pain relief and anti-inflammatory",
    },
    {
      id: "med-4",
      name: "Ibuprofen",
      nameHi: "इबुप्रोफेन",
      nameMr: "इबुप्रोफेन",
      class: "Anti-inflammatory",
      dose: "200-400mg",
      frequency: "3-4 times daily",
      description: "For pain and inflammation",
    },
    {
      id: "med-5",
      name: "Cetirizine",
      nameHi: "सेटीरिजीन",
      nameMr: "सेटीरिजीन",
      class: "Antihistamine",
      dose: "10mg",
      frequency: "Once daily",
      description: "For allergies and itching",
    },
    {
      id: "med-6",
      name: "Omeprazole",
      nameHi: "ओमेप्राजोल",
      nameMr: "ओमेप्राजोल",
      class: "Proton pump inhibitor",
      dose: "20-40mg",
      frequency: "Once daily",
      description: "For acid reflux",
    },
    {
      id: "med-7",
      name: "Metformin",
      nameHi: "मेटफोर्मिन",
      nameMr: "मेटफोर्मिन",
      class: "Antidiabetic",
      dose: "500mg-2g",
      frequency: "2-3 times daily",
      description: "For type 2 diabetes",
    },
    {
      id: "med-8",
      name: "Lisinopril",
      nameHi: "लिसिनोप्रिल",
      nameMr: "लिसिनोप्रिल",
      class: "ACE inhibitor",
      dose: "10-40mg",
      frequency: "Once daily",
      description: "For hypertension",
    },
  ],

  ddiPairs: [
    { drug1: "med-3", drug2: "med-4", severity: "high", description: "Both are NSAIDs, risk of GI bleeding" },
    { drug1: "med-1", drug2: "med-2", severity: "low", description: "No significant interaction" },
    { drug1: "med-7", drug2: "med-8", severity: "medium", description: "May cause hypoglycemia" },
  ],
}
